package apolo.repartidores.com.utilidades

import java.util.*

class TablasSincronizacion {

    fun listaSQLCreateTables(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0 , SentenciasSQL.createTableSvmPlanillaReparto())
        lista.add(1 , SentenciasSQL.createTableSvmVtSolDevCab())
        lista.add(2 , SentenciasSQL.createTableSvmVtSolDevDet())
        lista.add(3 , SentenciasSQL.createTableRpvMotivoRepCheckList())
        lista.add(4 , SentenciasSQL.createTableSvmPlanillaRepArt())
        lista.add(5 ,SentenciasSQL.createTableSvmVtMotivoRebote())
        lista.add(6 ,SentenciasSQL.createTableRvmStArticulos())
        lista.add(7 ,SentenciasSQL.createTableSvmVtMotivosSodDev())
        lista.add(8 ,SentenciasSQL.createTableSvmMotivoNoVenta())
        lista.add(9 ,SentenciasSQL.createTableRvmFacturaBonificada())
//        lista.add(10,SentenciasSQL.)
//        lista.add(11,SentenciasSQL.)
//        lista.add(12,SentenciasSQL.)
//        lista.add(13,SentenciasSQL.)
//        lista.add(14,SentenciasSQL.)
//        lista.add(15,SentenciasSQL.)
//        lista.add(16,SentenciasSQL.)
//        lista.add(17,SentenciasSQL.)
//        lista.add(18,SentenciasSQL.)
//        lista.add(19,SentenciasSQL.)
//        lista.add(20,SentenciasSQL.)
//        lista.add(21,SentenciasSQL.)
//        lista.add(22,SentenciasSQL.)
//        lista.add(23,SentenciasSQL.)
//        lista.add(24,SentenciasSQL.)
//        lista.add(25,SentenciasSQL.)
//        lista.add(26,SentenciasSQL.)
//        lista.add(27,SentenciasSQL.)
//        lista.add(28,SentenciasSQL.)
//        lista.add(29,SentenciasSQL.)
//        lista.add(30,SentenciasSQL.)
//        lista.add(31,SentenciasSQL.)
//        lista.add(32,SentenciasSQL.)
//        lista.add(33,SentenciasSQL.)
//        lista.add(34,SentenciasSQL.)
//        lista.add(35,SentenciasSQL.)
//        lista.add(36,SentenciasSQL.)
//        lista.add(37,SentenciasSQL.)
//        lista.add(38,SentenciasSQL.)
//        lista.add(39,SentenciasSQL.)
//        lista.add(40,SentenciasSQL.)
//        lista.add(41,SentenciasSQL.)
//        lista.add(42,SentenciasSQL.)
//        lista.add(43,SentenciasSQL.)
//        lista.add(44,SentenciasSQL.)
//        lista.add(45,SentenciasSQL.)
//        lista.add(46,SentenciasSQL.)
//        lista.add(47,SentenciasSQL.)
//        lista.add(48,SentenciasSQL.)
//        lista.add(49,SentenciasSQL.)

        return lista
    }

    fun listaCamposSincronizacion(): Vector<Vector<String>> {
        val lista : Vector<Vector<String>> = Vector()
        lista.add(0 ,camposSvmPlanillaReparto())
        lista.add(1 ,camposTablaSvmVtSolDevCab())
        lista.add(2 ,camposTablaSvmCtSolDevDet())
        lista.add(3 ,camposTablaRpvMotivoRepCheckList())
        lista.add(4 ,camposTablaSvmPlanillaRepArt())
        lista.add(5 ,camposTablaSvmVtMotivoRebote())
        lista.add(6 ,camposTablaRvmStArticulos())
        lista.add(7 ,camposTablaSvmVtMotivosSodDev())
        lista.add(8 ,camposTablaSrmMotivoNoVenta())
        lista.add(9 ,camposTablaRvmFacturaBonificada())
//        lista.add(10,camposTablaSvmMetasPuntoPorCliente())
//        lista.add(11,camposTablaSvmPedidosSinStockRep())
//        lista.add(12,camposTablaSvmNegociacionVenta())
//        lista.add(13,camposTablaSvmPedidosEnReparto())
//        lista.add(14,camposTablaSvmRebotesPorCliente())
//        lista.add(15,camposTablaSvmCiudades())
//        lista.add(16,camposTablaSvmTablaVisitas())
//        lista.add(17,camposTablaSvmTipoCliente())
//        lista.add(18,camposTablaSvmCondicionVentaCliente())
//        lista.add(19,camposTablaSvmPreciosFijos())
//        lista.add(20,camposTablaSvmLiqComisionVendedor())
//        lista.add(21,camposTablaSvmModuloComisionVend())
//        lista.add(22,camposTablaSvmDiasVisitaCliente())
//        lista.add(23,camposTablaSvmCondVentaVendedor())
//        lista.add(24,camposTablaSvmEvolDiariaVenta())
//        lista.add(25,camposTablaSvmVtvPreciosFijosMod())
//        lista.add(26,camposTablaStvCategoriaPalm())
//        lista.add(27,camposTablaSvmRetornoComentario())
//        lista.add(28,camposTablaSpmMotivoNoVenta())
//        lista.add(29,camposTablaSvmPromocionesPorPerfiles())
//        lista.add(30,camposTablaSvmListadoPedidos())
//        lista.add(31,camposTablaSvmDiasTomaFotoCliente())
//        lista.add(32,camposTablaSvmSegVisitasSemanal())
//        lista.add(33,camposTablaCcvMotivoSolTarjCred())
//        lista.add(34,camposTablaSvmPromocionesArtCab())
//        lista.add(35,camposTablaSvmPromocionesArtDet())
//        lista.add(36,camposTablaSvmMensajeConclusion())
//        lista.add(37,camposTablaSvmSurtidoEficiente())
//        lista.add(38,camposTablaSvmLiqPremiosVend())
//        lista.add(39,camposTablaSvmProduccionSemanalVend())
//        lista.add(40,camposTablaSvmRuteoSemanalClienteVend())
//        lista.add(41,camposTablaSvmCoberturaVisVendedores())
//        lista.add(42,camposTablaRhvLiquidacionFuerzaVenta())
//        lista.add(43,camposTablaSvmVtMotivosSodDev())
//        lista.add(44,camposTablaFvvLiqCuotaXUndNegVend())
//        lista.add(45,camposTablaSvmCoberturaMensualVend())
//        lista.add(46,camposTablaFvvCobSemanalVend())

        return lista
    }

    private fun camposSvmPlanillaReparto(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"TIP_PLANILLA")
        lista.add(2,"NRO_PLANILLA")
        lista.add(3,"FEC_PLANILLA")
        lista.add(4,"SER_COMPROBANTE")
        lista.add(5,"TIP_COMPROBANTE")
        lista.add(6,"NRO_COMPROBANTE")
        lista.add(7,"COD_VEHICULO")
        lista.add(8,"DESC_VEHICULO")
        lista.add(9,"COD_CHOFER")
        lista.add(10,"DESC_CHOFER")
        lista.add(11,"COD_REPARTIDOR")
        lista.add(12,"COD_CLIENTE")
        lista.add(13,"COD_SUBCLIENTE")
        lista.add(14,"NOM_CLIENTE")
        lista.add(15,"NOM_SUBCLIENTE")
        lista.add(16,"TOT_COMPROBANTE")
        lista.add(17,"COD_MONEDA")
        lista.add(18,"SIGLAS")
        lista.add(19,"TIPO")
        lista.add(20,"DIR_CLIENTE")
        lista.add(21,"LATITUD")
        lista.add(22,"LONGITUD")
        lista.add(23,"DESC_ZONA")
        lista.add(24,"DESC_CIUDAD")
        lista.add(25,"IND_REENVIAR")
        lista.add(26,"HACER_SD")
        lista.add(27,"COD_VENDEDOR")
        lista.add(28,"MARC_SALIDA")
        lista.add(29,"IND_ENTREGA")
        lista.add(30,"IND_CERRADO")
        lista.add(31,"COD_CONDICION_VENTA")
        lista.add(32,"DECIMALES")
        return lista
    }
    private fun camposTablaSvmVtSolDevCab(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"TIP_COMPROBANTE")
        lista.add(1,"SER_COMPROBANTE")
        lista.add(2,"NRO_COMPROBANTE")
        lista.add(3,"COD_CLIENTE")
        lista.add(4,"NOM_CLIENTE")
        lista.add(5,"TIP_PLANILLA")
        lista.add(6,"NRO_PLANILLA")
        lista.add(7,"SIGLAS")
        lista.add(8,"DECIMALES")
        lista.add(9,"TOT_COMPROBANTE")
        return lista
    }
    private fun camposTablaSvmCtSolDevDet(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"TIP_COMPROBANTE")
        lista.add(1,"SER_COMPROBANTE")
        lista.add(2,"NRO_COMPROBANTE")
        lista.add(3,"COD_ARTICULO")
        lista.add(4,"DESC_ARTICULO")
        lista.add(5,"CANTIDAD")
        lista.add(6,"COD_UNIDAD_MEDIDA")
        lista.add(7,"DESC_UNID")
        lista.add(8,"MONTO_TOTAL_CONIVA")
        lista.add(9,"COD_MOTIVO")
        lista.add(10,"DESC_MOTIVO")
        return lista
    }
    private fun camposTablaRpvMotivoRepCheckList(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"DESC_MOTIVO")
        lista.add(3,"IND_OBLIG")
        lista.add(4,"LATITUD")
        lista.add(5,"LONGITUD")
        lista.add(6,"DATOS")
        return lista
    }
    private fun camposTablaSvmPlanillaRepArt(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"TIP_PLANILLA")
        lista.add(2,"NRO_PLANILLA")
        lista.add(3,"SER_COMP")
        lista.add(4,"TIP_COMP")
        lista.add(5,"NRO_COMP")
        lista.add(6,"DECIMALES")
        lista.add(7,"COD_ARTICULO")
        lista.add(8,"DESC_ARTICULO")
        lista.add(9,"NRO_ORDEN")
        lista.add(10,"COD_UNIDAD_MEDIDA")
        lista.add(11,"DESC_UNI_MED")
        lista.add(12,"MULT")
        lista.add(13,"CANTIDAD")
        lista.add(14,"PRECIO_UNITARIO_C_IVA")
        lista.add(15,"IND_BON_CAU")
        lista.add(16,"IND_BON")
        lista.add(17,"PRECIO_LISTA")
        lista.add(18,"PORC_DESC_VAR")
        lista.add(19,"PORC_DESC_FIN")
        lista.add(20,"DESCUENTO_VAR")
        lista.add(21,"DESCUENTO_FIN")
        lista.add(22,"PRECIO_DIFERENCIA")
        lista.add(23,"TIP_COMPROBANTE_REF")
        lista.add(24,"SER_COMPROBANTE_REF")
        lista.add(25,"NRO_COMPROBANTE_REF")
        lista.add(26,"TIPO_PROMOCION")
        lista.add(27,"NRO_PROMOCION")
        lista.add(28,"IND_INPASA")
        lista.add(29,"PRECIO_UB")
        return lista
    }
    private fun camposTablaSvmVtMotivoRebote(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_PENAL")
        lista.add(2,"DESCRIPCION")
        return lista
    }
    private fun camposTablaRvmStArticulos(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_ARTICULO")
        lista.add(2,"DESC_ARTICULO")
        lista.add(3,"COD_UNIDAD_REL")
        lista.add(4,"REFERENCIA")
        lista.add(5,"COD_BARRA")
        lista.add(6,"MULT")
        lista.add(7,"IND_BASICO")
        return lista
    }
    private fun camposTablaSvmVtMotivosSodDev(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"DESC_MOTIVO")
        return lista
    }
    private fun camposTablaSrmMotivoNoVenta(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"COD_EMPRESA")
        lista.add(1,"COD_MOTIVO")
        lista.add(2,"CIERRE_MARC")
        lista.add(3,"DESC_MOTIVO")
        return lista
    }
    private fun camposTablaRvmFacturaBonificada(): Vector<String> {
        val lista : Vector<String> = Vector()
        lista.add(0,"cod_empresa")
        lista.add(1,"ser_comprobante")
        lista.add(2,"tip_comprobante")
        lista.add(3,"nro_comprobante")
        lista.add(4,"ser_comprobante_ref")
        lista.add(5,"tip_comprobante_ref")
        lista.add(6,"nro_comprobante_ref")
        lista.add(7,"ind_bon")
        lista.add(8,"ind_bon_cau")
        return lista
    }

//    fun camposTablaS(): Vector<String> {
//        var lista : Vector<String> = Vector()
//        lista.add(0,"")
//        lista.add(1,"")
//        lista.add(2,"")
//        lista.add(3,"")
//        lista.add(4,"")
//        lista.add(5,"")
//        lista.add(6,"")
//        lista.add(7,"")
//        lista.add(8,"")
//        lista.add(9,"")
//        lista.add(10,"")
//        lista.add(11,"")
//        lista.add(12,"")
//        lista.add(13,"")
//        lista.add(14,"")
//        lista.add(15,"")
//        lista.add(16,"")
//        lista.add(17,"")
//        lista.add(18,"")
//        lista.add(19,"")
//        lista.add(20,"")
//        lista.add(21,"")
//        lista.add(22,"")
//        lista.add(23,"")
//        lista.add(24,"")
//        lista.add(25,"")
//        lista.add(26,"")
//        lista.add(27,"")
//        lista.add(28,"")
//        lista.add(29,"")
//        return lista
//    }

}
